const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const CLEAR_LOGIN_ERR = 'CLEAR_LOGIN_ERR';
const LOGOUT = 'LOGOUT';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';

export {
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    CLEAR_LOGIN_ERR,
    LOGOUT,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
};
